species: arabidopsis

seq_info:
  type: iCLIP
  mode: SE

raw_reads: /data1/HJY/raw_data/HJY_Mecp2_iCLIP_omicscore20180507/Undetermined_S0_L006_R1_001.fastq.gz

# format of sample names: name.barcode
samples:
  - Mecp2_ctrl_rep1.GGCG
  - Mecp2_ctrl_rep2.AACC
  - Mecp2_ctrl_rep3.CGGA
  - Mecp2_expt_rep1.TGGC
  - Mecp2_expt_rep2.CCAC
  - Mecp2_expt_rep3.GGCA

groups:
  - Mecp2_ctrl
  - Mecp2_expt

adapt: TGAGATCGGAAG

cpu: 8

mismatch: 2

FDR: 0.05

cluster_dist: 30

conda_path: /home/xfu/miniconda2/envs/icount/bin

genome: /home/xfu/Gmatic7/iCount/mm88

annotation: /home/xfu/Gmatic7/iCount/mus_musculus.88.gtf.gz

segmentation: /home/xfu/Gmatic7/iCount/mm88seg.gtf.gz

fai: /home/xfu/Gmatic7/iCount/mus_musculus.88.fa.gz.fai

Rscript_path: /home/xfu/R/3.2.4/bin/Rscript

IGV: /home/xfu/igv/genomes/mm10.genome
