species: mouse

seq_info:
  type: iCLIP
  mode: SE

raw_reads: /data1/HJY/raw_data/HJY_Mecp2_iCLIP_omicscore20180507/Undetermined_S0_L006_R1_001.fastq.gz

# format of sample names: name.barcode
samples:
  - Mecp2_ctrl_rep1.GGCG
  - Mecp2_ctrl_rep2.AACC
  - Mecp2_ctrl_rep3.CGGA
  - Mecp2_expt_rep1.TGGC
  - Mecp2_expt_rep2.CCAC
  - Mecp2_expt_rep3.GGCA

barcode: 3+4+2
#barcode: 5+6+4

adapt: TGAGATCGGAAG

adapt_error: 0.25

cpu: 8

mismatch: 2

FDR: 0.05

cluster_dist: 30

conda_path: /home/xfu/miniconda2/envs/icount/bin

Rscript_path: /home/xfu/R/3.2.4/bin/Rscript

genome: /home/xfu/Gmatic7/iCount/mm88
#genome: /home/xfu/Gmatic7/iCount/hs88

annotation: /home/xfu/Gmatic7/iCount/mus_musculus.88.gtf.gz
#annotation: /home/xfu/Gmatic7/iCount/homo_sapiens.88.gtf.gz

segmentation: /home/xfu/Gmatic7/iCount/mm88seg.gtf.gz
#segmentation: /home/xfu/Gmatic7/iCount/hs88seg.gtf.gz

fai: /home/xfu/Gmatic7/iCount/mus_musculus.88.fa.gz.fai
#fai: /home/xfu/Gmatic7/iCount/homo_sapiens.88.fa.gz.fai

IGV: /home/xfu/igv/genomes/mm10.genome
#IGV: /home/xfu/igv/genomes/hg38.genome
